on:
  workflow_dispatch:
    inputs:
      JobID:
        description: "ID of the job"
        required: true
      Package:
        description: "Package location"
        required: true
      Reference:
        description: Version control reference, if any
        required: false
name: Building Package
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build ${{ github.event.inputs.Package }} ${{ github.event.inputs.Reference }}
        run: |
          curl -X POST https://store.bramble.run/job/${{ github.event.inputs.JobID }}/register \
            -H 'Content-Type: application/json' \
            -d '{"RunID": ${{ github.run_id }}}'
          go run . publish --upload --local ${{ github.event.inputs.Package }} ${{ github.event.inputs.Reference }}
