on:
  workflow_dispatch:
    inputs:
      JobID:
        description: "ID of the job"
        required: true
      Package:
        description: "Package location"
        required: true
      Reference:
        description: Version control reference, if any
        required: false
name: Builder ${{ github.event.inputs.Package }} ${{ github.event.inputs.Reference }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build ${{ github.event.inputs.Package }} ${{ github.event.inputs.Reference }}
        run: |
          curl -X POST https://store.bramble.run/job/${{ github.event.inputs.JobID }}/register \
            -H 'Content-Type: application/json' \
            -d '{"RunID": ${{ github.run_id }}}'
          echo ${{ github.event.inputs.JobID }}
          echo ${{ github.event.inputs.Package }}
          echo ${{ github.event.inputs.Reference }}
