on:
  workflow_dispatch:
    inputs:
      JobID:
        description: "ID of the job"
        required: true
      Package:
        description: "Package location"
        required: true
      Reference:
        description: Version control reference, if any
        required: false
name: Builder
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run all tests
        run: |
          echo ${{ github.event.inputs.JobID }}
          echo ${{ github.event.inputs.Reference }}
