name: Publishing Release
on: [push]
permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for goreleaser
      - name: Publish release
        run: |
          docker build -t goreleaser -f .github/workflows/goreleaser.Dockerfile .github/workflows/
          docker run \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v $(pwd):/opt \
            --workdir=/opt \
            goreleaser/goreleaser release --rm-dist
