on: [push]
name: Running Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      # for your debugging needs, will pause job and print ssh connection string
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Run all tests
        run: |
          make ci_test
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        # if: github.ref == 'refs/heads/main'
      - name: Publish release
        # if: github.ref == 'refs/heads/main'
        run: |
          version="v$(bramble config version)"

          # Exit if version is not different from the previous tag
          if [ $version = "${{ steps.get-latest-tag.outputs.tag }}" ]; then exit 0; fi

          docker build -t goreleaser -f .github/workflows/goreleaser.Dockerfile .github/workflows/
          docker run \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -v $(pwd):/opt \
            --workdir=/opt \
            goreleaser release --rm-dist --version $(bramble config version)
