on: [push]
name: Running Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      # for your debugging needs, will pause job and print ssh connection string
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - name: Run all tests
        run: |
          make ci_test
